Remove tech jargon from photo picker related content
commons-app/commons-app.github.io pull request #60
Opened 2023-07-27 09:59 UTC by RitikaPahwa4444

2023-08-23 17:45 UTC, sivaraam requested changes
Thanks for the change!

I've left some comments. Kindly take a look at them.

2023-08-23 17:45 UTC, sivaraam commented on docs.html
> +        <p>In order to preserve location information, we decided to go with the system file picker by default for the Document based picker and disabled the new Android picker.</p>
> In order to preserve location information, we decided to go with the system file picker by default for the Document based picker and disabled the new Android picker.

I suppose this phrase could be improved a bit. May be tweak it like:

> In order to preserve location information, we decided to go with the Document based picker by default and skipped the new Android picker.

(note: as you know we can't disable the new photo picker)

2023-08-23 17:45 UTC, sivaraam commented on docs.html
> +        <p><b>New Android Picker:</b>
May be clarify that only the "New Android picker with takeover" is problematic ? 

When takeover is not happening, the location conventional GET_CONTENT picker kicks in which does not have location loss issues.

2023-08-23 17:45 UTC, sivaraam commented on docs.html
>                  <li><b>Merits:</b> Lists all image providers as marked in red in the figure above, user-friendly interface.</li>
I'm kind of unsure. Does this merit really apply to the new photo picker with takeover ? If not, we may need to reconsider the phrasing 🤔

2023-08-23 17:45 UTC, sivaraam commented on docs.html
> +        <p>The Commons app lets you pick what picture(s) you want to upload, using either the camera button or what we call a "picker". The "custom picker" has an icon that includes a small Commons l
> and the "new Android picker" ...

In retrospect, it is incorrect to refer to the GET_CONTENT picker as  the "new Android picker" since it has been there for a long time. The actual new picker is one that was recently added and appears in the GET_CONTENT intent when takeover is enabled.

So, I believe it makes sense to distinguish the same so that users could clearly understand the different. Could you kindly go through the content once and rephrase it to distinguish both of them better ? I guess we could use the term "media picker" to refer to the old GET_CONTENT picker and "new media picker" for the one shown when takeover is enabled. What do you think ?

2023-08-24 05:57 UTC, RitikaPahwa4444 commented on docs.html
> +        <p><b>New Android Picker:</b>
The one without takeover isn't new. Any special name you would like to suggest for that one? We are skipping GET_CONTENT altogether, explaining takeover without it sounds weird.

2023-08-24 05:59 UTC, RitikaPahwa4444 commented on docs.html
>                  <li><b>Merits:</b> Lists all image providers as marked in red in the figure above, user-friendly interface.</li>
It always does. I've explained how users can get these providers by using 'Browse'. That's not possible with the document style picker.

2023-08-24 06:02 UTC, RitikaPahwa4444 commented on docs.html
> +        <p>The Commons app lets you pick what picture(s) you want to upload, using either the camera button or what we call a "picker". The "custom picker" has an icon that includes a small Commons l
Since the dialog you added calls it "new Android picker", I avoid introducing new terms like media picker, or something similar.

2023-08-24 17:01 UTC, sivaraam commented on docs.html
>                  <li><b>Merits:</b> Lists all image providers as marked in red in the figure above, user-friendly interface.</li>
The way the merit is phrased makes it sound as if it applies to new media picker itself, does it not ? I was thinking we might need to tweak it a bit (like making it explicit that the merit applies only to traditional media picker?).

We could also clarify the demerit applies only to new media picker (which appears upon takeover).

2023-08-24 17:06 UTC, sivaraam commented on docs.html
> +        <p><b>New Android Picker:</b>
> We are skipping GET_CONTENT altogether, explaining takeover without it sounds weird.

I could understand this. The word "takeover" seems to make little sense when we're trying to keep the content less technical. Could you look into phrasing the content by avoiding the mention of the same (except in the command of course)?

For instance, the following phrase :

> The new Android picker that you may try in the Contributions and Nearby tab, it varies from device to device:
> The new Android picker without takeover
> The new Android picker with takeover
... could be tweaked as ...

> The media picker that you may try in the Contributions and Nearby tab, it varies from device to device:
> The traditional media picker  (does not strip location)
> The new media picker (strips location)

2023-08-24 17:07 UTC, sivaraam commented on docs.html
> +        <p>The Commons app lets you pick what picture(s) you want to upload, using either the camera button or what we call a "picker". The "custom picker" has an icon that includes a small Commons l
We could change the dialog text if necessary, Ritika. Let that not be a reason to compromise on the readability / understandability of the text.

2023-08-24 17:08 UTC, RitikaPahwa4444 commented on docs.html
> +        <p><b>New Android Picker:</b>
Thank you for the example. I'll modify this.

2023-08-24 17:14 UTC, RitikaPahwa4444 commented on docs.html
>                  <li><b>Merits:</b> Lists all image providers as marked in red in the figure above, user-friendly interface.</li>
> The way the merit is phrased makes it sound as if it applies to new media picker itself, does it not ?

Yes. No doubt it provides a way to get them via 'Browse'. Moreover, they are planning to extend the support [[source](https://android-developers.googleblog.com/2023/04/photo-picker-everywhere.html)]:
> Later this year, the photo picker will seamlessly support cloud storage providers like Google Photos, allowing users to select their remote content without having to leave your app, and without any code change on the developers side.
Could be modified later once they do.

2023-09-09 17:24 UTC, sivaraam approved these changes

2023-09-09 17:24 UTC, sivaraam commented
Looks good. Thanks, Ritika! 🙂

2023-09-09 17:24 UTC, merged